# ~/.config/helix/config.toml

theme = "Ashen"

[editor]
line-number = "absolute"
mouse = true
cursorline = true
bufferline = "multiple"
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
# save shortcut (ctrl + s)
C-s = ":w"

# buffer transition
"A-," = "goto_previous_buffer"
"A-." = "goto_next_buffer"
"A-w" = ":buffer-close"
